export default {
  token: localStorage.getItem('auth-token') || '',
  isLoading: false,
  name: '',
  role: '',
  giftcard: {},
  recs: [],
  title: 'Gift Card',
  icon: 'card_giftcard',
  selected: [],
  isModalOpened: false,
  editingRec: {},
  backupRec: {},
  cols: [
    {
      name: 'edit',
      align: 'left',
      field: 'edit',
      width: '34px',
    },
    {
      name: 'userName',
      label: 'User Name',
      align: 'left',
      field: 'userName',
      sortable: true,
    },
    {
      name: 'amount',
      label: 'Amount',
      align: 'left',
      field: 'amount',
      sortable: true,
    },
    {
      name: 'expiry',
      label: 'Expiry',
      align: 'left',
      field: 'expiry',
      sortable: true,
    },
    {
      name: 'createdAt',
      label: 'Create Date',
      align: 'left',
      field: 'createdAt',
      sortable: true,
    },
    {
      name: 'updatedAt',
      label: 'Update Date',
      align: 'left',
      field: 'updatedAt',
      sortable: true,
    },
  ],
  fields: [
    {
      name: 'id',
      hidden: true,
    },
    {
      name: 'code',
      hidden: true,
    },
    {
      name: 'userName',
      label: 'User Name',
      type: 'text',
      icon: 'account_box',
    },
    {
      name: 'amount',
      label: 'Amount',
      type: 'text',
    },
    {
      name: 'expiry',
      label: 'Expiry',
      type: 'text',
    },
    {
      name: 'createdAt',
      label: 'Create Date',
      type: 'text',
    },
    {
      name: 'updatedAt',
      label: 'Update Date',
      type: 'text',
    },
  ],
}
